RAC-5347 Add stages for Docker Post test pipeline

diff --git a/test.sh.in b/test.sh.in
--- a/test.sh.in
+++ b/test.sh.in
@@ -218,6 +218,28 @@ runTests() {
   args=()
   if [ ! -z "$1" ];then
       args+="$1"
+  if [ "$RUN_FIT_TEST" == true ] ; then
+     cd ${WORKSPACE}/RackHD/test
+     #TODO Parameterize FIT args
+     tstack="${TEST_STACK}"
+     read hwarray<<<"${EXTRA_HW}"
+     for item in $hwarray; do
+         if [ "${item}" == "ucs" ] && [ "${TEST_STACK}" == "-stack vagrant" ]; then
+             tstack="-stack vagrant_ucs"
+         fi
+     done
+     python run_tests.py -test deploy/rackhd_stack_init.py ${tstack} -xunit
+     if [ $? -ne 0 ]; then
+         echo "Test FIT failed running deploy/rackhd_stack_init.py"
+         exit 1
+     fi
+     python run_tests.py ${TEST_GROUP} ${tstack} -v 4 -xunit
+     if [ $? -ne 0 ]; then
+         echo "Test FIT failed running smoke test"
+         exit 1
+     fi
+     mkdir -p ${WORKSPACE}/xunit-reports
+     cp *.xml ${WORKSPACE}/xunit-reports
   fi
   if [ "$RUN_FIT_TEST" == true ] ; then
       fitSmokeTest "${args}"
